Maps part 2
mohamedally/team22 pull request #12
Opened 2019-03-10 21:36 UTC by Oporto

Finished the requirements for the guided project: Maps part 2.
Things to improve upon for next version:
- Restraining the amount of markers added to the map (right now its all)
- Use geocode API to get location data on all universities for data set
- Style window that pops up when clicking on university

2019-03-11 03:01 UTC, mohamedally requested changes

2019-03-11 03:01 UTC, mohamedally commented on src/main/java/com/google/codeu/servlets/UniversityDataServlet.java
> +            System.out.println(line);
after testing this out maybe we should remove the printing??

2019-03-11 15:24 UTC, Oporto commented on src/main/java/com/google/codeu/servlets/UniversityDataServlet.java
> +            System.out.println(line);
I already tested it and forgot to remove it!

2019-03-12 15:24 UTC, Oporto reviewed
Should be all set now

2019-03-12 15:38 UTC, mohamedally approved these changes

2019-03-12 16:15 UTC, merged